routes/admin.php
<?php

Route::group(['middleware' => 'admin'], function() {
    Route::get('/home', 'Admin\HomeController@index')->name('home');
    Route::post('/kendo/piechart', 'Admin\HomeController@get_pie_chart_data')->name('kendo.piechart');
    Route::post('/kendo/barchart', 'Admin\HomeController@get_bar_chart_data')->name('kendo.barchart');
    Route::get('/profile', 'Admin\HomeController@get_profile_setting')->name('profile');
    Route::post('/profile', 'Admin\HomeController@update_profile_setting');
    Route::post('/time_zone', 'Admin\HomeController@update_time_zone')->name('time_zone');
    Route::get('/customer', 'Admin\CustomersController@get_customer_view')->name('customer');
    Route::post('/customer', 'Admin\CustomersController@make_new_customer');
    Route::post('/customer/update', 'Admin\CustomersController@update_customer')->name('update_customer');
    Route::post('/customer/delete', 'Admin\CustomersController@delete_customer')->name('delete_customer');
    Route::post('/customer/status', 'Admin\CustomersController@change_customer_status')->name('change_customer_status');
    Route::post('/customer/capacity', 'Admin\CustomersController@update_customer_capacity')->name('update_customer_capacity');
    Route::post('/customer/capacity/history', 'Admin\CustomersController@customer_capacity_history')->name('customer_capacity_history');
    Route::post('/customer/prefix', 'Admin\PrefixController@set_customer_prefix')->name('customer_prefix');
    Route::post('/customer/prefix/rate', 'Admin\PrefixController@get_customer_prefix_rate')->name('customer_prefix_rate');
    Route::get('/user/login/{customer}', 'HomeController@customer_login')->name('customer_login');
    Route::post('/user/key', 'Admin\CustomersController@update_customer_key')->name('customer_key');

    Route::get('/route', 'Admin\RouteController@get_route_view')->name('route');
    Route::post('/route', 'Admin\RouteController@make_route');
    Route::get('/route/smsbox', 'Admin\RouteController@get_smsbox_route_view')->name('smsbox');

    Route::post('/route/update', 'Admin\RouteController@update_route')->name('update_route');
    Route::post('/route/delete', 'Admin\RouteController@delete_route')->name('delete_route');
    Route::post('/route/status', 'Admin\RouteController@change_status')->name('change_status');
    Route::post('/route/capacity', 'Admin\RouteController@add_route_capacity')->name('add_route_capacity');
    Route::post('/route/capacity/history', 'Admin\RouteController@route_capacity_history')->name('route_capacity_history');
    Route::post('/route/prefix', 'Admin\PrefixController@set_route_prefix')->name('route_prefix');
    Route::post('/route/prefix/rate', 'Admin\PrefixController@get_route_prefix_rate')->name('route_prefix_rate');

    Route::get('/route/assign', 'Admin\RouteController@get_route_assign')->name('route_assign');
    Route::post('/route/assign', 'Admin\RouteController@make_route_assign');
    Route::post('/route/assign/update', 'Admin\RouteController@update_route_assign')->name('update_route_assign');
    Route::post('/route/assign/delete', 'Admin\RouteController@delete_route_assign')->name('delete_route_assign');
    Route::post('/route/assign/update/status', 'Admin\RouteController@update_route_assign_status')->name('update_route_assign_status');

    Route::group(['prefix' => 'setting'], function() {
        Route::get('/', function (){ return "This is Setting"; })->name('setting');
        Route::get('prefix', 'Admin\PrefixController@get_prefix_settings_view')->name('prefix_setting');
        Route::post('prefix', 'Admin\PrefixController@set_prefix_settings');
        Route::post('prefix/update', 'Admin\PrefixController@update_prefix_settings')->name("update_prefix_setting");
        Route::post('prefix/status', 'Admin\PrefixController@change_prefix_status')->name('change_prefix_status');
        Route::group(['prefix' => 'otp'], function() {
            Route::get('/', 'Admin\OtpVendorController@get_otp_vendor')->name('otp_vendor');
            Route::post('/', 'Admin\OtpVendorController@make_otp_vendor');
            Route::post('/vendor/update', 'Admin\OtpVendorController@update_vendor')->name('update_vendor');
            Route::post('/vendor/status', 'Admin\OtpVendorController@change_otp_vendor_status')->name('change_otp_vendor_status');
            Route::post('/vendor/delete', 'Admin\OtpVendorController@delete_otp_vendor')->name('delete_otp_vendor');

            Route::get('/string/input', 'Admin\OtpStringController@otp_input_string')->name('otp_input_string');
            Route::post('/string/input', 'Admin\OtpStringController@make_input_string');
            Route::post('/string/input/status', 'Admin\OtpStringController@change_input_string_status')->name('change_input_string_status');
            Route::post('/string/input/update', 'Admin\OtpStringController@update_input_string')->name('update_input_string');
            Route::post('/string/input/delete', 'Admin\OtpStringController@delete_input_string')->name('delete_input_string');

            Route::get('/string/output', 'Admin\OtpOutputStringController@otp_output_string')->name('otp_output_string');
            Route::post('/string/output', 'Admin\OtpOutputStringController@make_otp_output_string');
            Route::post('/string/output/update', 'Admin\OtpOutputStringController@update_output_string')->name('update_output_string');
            Route::post('/string/output/delete', 'Admin\OtpOutputStringController@delete_output_string')->name('delete_output_string');
            Route::post('/string/output/status', 'Admin\OtpOutputStringController@change_output_string_status')->name('change_output_string_status');


        });
    });
    Route::group(['middleware' => 'admin','prefix' => 'report'], function() {
        Route::get('/overcapacity', 'Admin\OverCapacityController@get_over_capacity')->name('over_capacity');
        Route::get('/smpp', 'Admin\SMPPController@get_smpp_report')->name('smpp');
        Route::get('/', 'Admin\MessageController@get_daily_report')->name('report');
        Route::post('/', 'Admin\MessageController@get_daily_report');
        Route::get('/date/range', 'Admin\MessageController@get_range_report_view')->name('range_report');
        Route::post('/date/range', 'Admin\MessageController@get_range_report');
        Route::get('/customer', 'Admin\MessageController@get_customer_report_view')->name('customer_report');
        Route::post('/customer', 'Admin\MessageController@get_customer_report');
    });

    Route::group(['middleware' => 'admin','prefix' => 'setting/telerivet'], function() {
        Route::get('/', 'API\TelerivetApiController@get_telerivet_info')->name('get_telerivet_info');
        Route::post('/', 'API\TelerivetApiController@make_telerivet_api');
        Route::post('/update', 'API\TelerivetApiController@update_telerivet_api')->name('update_telerivet_info');
        Route::post('/status', 'API\TelerivetApiController@update_telerivet_status')->name('update_telerivet_status');
        Route::post('/delete', 'API\TelerivetApiController@delete_telerivet_api')->name('delete_telerivet_api');

    });


    Route::group(['prefix' => 'shortlink','as'=>'shortlink.'], function () {
        Route::get('/', 'ShortLink\ShortLinkController@get_bitly_view')->name('shortlink');
        Route::post('/', 'ShortLink\ShortLinkController@make_new_bitly');
        Route::post('/update', 'ShortLink\ShortLinkController@update_bitLay_info')->name('bitLay_update');
        Route::post('/delete', 'ShortLink\ShortLinkController@delete_bitLay_info')->name('bitLay_delete');
        Route::post('/status', 'ShortLink\ShortLinkController@update_bitlay_status')->name('change_bit_lay_status');
        Route::get('/test', 'ShortLink\ShortLinkController@test_short_link');
        Route::get('/setting', 'ShortLink\ShortLinkController@get_regx_setting')->name('setting');
        Route::post('/setting', 'ShortLink\ShortLinkController@make_new_regx');
        Route::post('/setting/update', 'ShortLink\ShortLinkController@update_regular_expression')->name('update_setting');
        Route::post('/setting/delete', 'ShortLink\ShortLinkController@delete_regular_expression')->name('delete_setting');
        Route::post('/setting/status', 'ShortLink\ShortLinkController@change_regx_status')->name('change_regx_status');
        Route::get('/links', 'ShortLink\ShortLinkController@get_short_urls')->name('link');

    });
});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(['as'=>'customer.'], function () {
    Route::get('/login', 'CustomerAuth\LoginController@showLoginForm')->name('login');
    Route::get('/', 'CustomerAuth\LoginController@showLoginForm');
    Route::post('/login', 'CustomerAuth\LoginController@login');
    Route::post('/logout', 'CustomerAuth\LoginController@logout')->name('logout');
    Route::get('/logout', 'CustomerAuth\LoginController@logout');
});

Route::group(['prefix' => 'admin','as'=>'admin.'], function () {
    Route::get('/login', 'AdminAuth\LoginController@showLoginForm')->name('login');
    Route::get('/', 'AdminAuth\LoginController@showLoginForm');
    Route::post('/login', 'AdminAuth\LoginController@login');
    Route::get('/logout', 'AdminAuth\LoginController@logout');
    Route::post('/logout', 'AdminAuth\LoginController@logout')->name('logout');

});

Route::get('/login', 'CustomerAuth\LoginController@showLoginForm')->name('login');
Route::post('/login', 'CustomerAuth\LoginController@login');

resources/views/admin/include/footer.blade.php
<!-- Main Footer -->
<footer class="main-footer">
    <!-- To the right -->
   {{-- <div class="pull-right hidden-xs">
        Officer CRM DC Project
    </div>--}}
    <!-- Default to the left -->
    <strong>Copyright &copy; {{date('Y')}} <a target="_blank" href="http://themehappy.com/">ThemeHappy</a>.</strong> All rights
    reserved.
</footer>

<!-- Add the sidebar's background. This div must be placed
immediately after the control sidebar -->
<div class="control-sidebar-bg">
</div>

resources/views/admin/include/header.blade.php
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<!-- Tell the browser to be responsive to screen width -->
<meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">

<!-- Font Awesome -->
<link rel="stylesheet" href="{{asset('assets/css/font-awesome.min.css')}}">
<!-- Ionicons -->
<link rel="stylesheet" href="{{asset('assets/css/ionicons.min.css')}}">
<!-- Select2 -->
<link rel="stylesheet" href="{{asset('assets/css/select2.min.css')}}">
<!-- Bootstrap -->
<link rel="stylesheet" href="{{asset('assets/css/bootstrap.min.css')}}">

<!-- AdminLTE Skins. We have chosen the skin-blue for this starter
      page. However, you can choose any other skin. Make sure you
      apply the skin class to the body tag so the changes take effect. -->
<link rel="stylesheet" href="{{asset('assets/css/_all-skins.min.css')}}">

<!-- Theme style -->
<link rel="stylesheet" href="{{asset('assets/css/AdminLTE.min.css')}}">

<!-- Custom style -->

<link rel="stylesheet" href="{{asset('assets/css/style.css')}}">
<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
<!-- Google Font -->
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">

resources/views/admin/include/javascript_bar.blade.php
<!-- REQUIRED JS SCRIPTS -->

<!-- jQuery 3 -->
<script src="{{asset('assets/js/jquery.min.js')}}"></script>
<!-- Bootstrap 3.3.7 -->
<script src="{{asset('assets/js/bootstrap.min.js')}}"></script>
<!-- select2 -->
<script src="{{asset('assets/js/select2.full.min.js')}}"></script>

<!-- AdminLTE App -->
<script src="{{asset('assets/js/adminlte.min.js')}}"></script>
{{--Select 2 js--}}
<script src="{{asset('assets/js/select2.min.js')}}"></script>
<!-- DC custom -->
<script src="{{asset('assets/js/custom.js')}}"></script>


<script>
    //click for get more details msg
    $(".more").click(function () {
        $(this).parent().find('.hidden').removeClass('hidden');
        $(this).addClass('hidden');
    });

    //click for get more details msg
    $(".less").click(function () {
        $(this).parent().find('.hidden').removeClass('hidden');
        $(this).parent().find('p').addClass('hidden');
        $(this).addClass('hidden');
    });
    $(document).ready(function() {
        $(".time_zone").change(function () {
          //  $(".time_zone_form").submit();
            $(this).parent().submit();
        });
        $('.js-example-basic-single').select2();
        $('[data-toggle="tooltip"]').tooltip();
        $('[data-toggle="tooltip"]').click(function () {
            $(this).tooltip("hide")
        });


    });


</script>
<!-- Optionally, you can add Slimscroll and FastClick plugins.
     Both of these plugins are recommended to enhance the
     user experience. -->

resources/views/admin/include/left_sidebar.blade.php
<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">

    <section class="sidebar">
        <!-- Sidebar Menu -->
        <ul class="sidebar-menu" data-widget="tree">
            <!--<li class="header">HEADER</li>->
            <!-- Optionally, you can add icons to the links -->
            <li @if(URL::current()==route('home')) class="active" @endif>
                <a href="{{route('home')}}">
                    <i class="fa fa-home" aria-hidden="true"></i> <span>Dashboard</span>
                </a>
            </li>
            <li @if(URL::current()==route('customer')) class="active" @endif>
                <a href="{{route('customer')}}">
                    <i class="fa fa-user" aria-hidden="true"></i> <span>Customer</span>
                    <span class="pull-right-container">
            </span>
                </a>
            </li>


            <li @if(strpos(URL::current(), route('route')) !== false)  class="active treeview" @else
            class="treeview" @endif>
                <a href="javascript:void(0);">
                    <i class="fa fa-retweet" aria-hidden="true"></i> <span>Vendor</span>
                    <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
                </a>
                <ul  class="treeview-menu">
                    <li @if(URL::current()==route('route')) class="active" @endif>
                        <a href="{{route('route')}}">
                            <i class="fa fa-comments" aria-hidden="true"></i> <span>SMS Gateway</span>
                            <span class="pull-right-container"></span>
                        </a>
                    </li>
                </ul>
            </li>
            <li @if(URL::current()==route('route_assign')) class="active" @endif>
                <a href="{{route('route_assign')}}">
                    <i class="fa fa-random" aria-hidden="true"></i> <span>Routing</span>
                    <span class="pull-right-container">
            </span>
                </a>
            </li>

            <li @if(strpos(URL::current(), route('report')) !== false)  class="active treeview" @else
            class="treeview" @endif>
                <a href="javascript:void(0);">
                    <i class="fa fa-files-o" aria-hidden="true"></i> <span>Reports</span>
                    <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
                </a>
                <ul  class="treeview-menu">
                    <li @if(URL::current()==route('report'))  class="active" @endif>
                        <a href="{{route('report')}}">
                            <i class="fa fa-circle-o"></i> Daily Report
                        </a>
                    </li>
                    <li @if(URL::current()==route('range_report'))  class="active" @endif>
                        <a href="{{route('range_report')}}">
                            <i class="fa fa-circle-o"></i> Range Report
                        </a>
                    </li>
                    <li @if(URL::current()==route('customer_report'))  class="active" @endif>
                        <a href="{{route('customer_report')}}">
                            <i class="fa fa-circle-o"></i> Report by Customer
                        </a>
                    </li>
                    <li @if(URL::current()==route('smpp'))  class="active" @endif>
                        <a href="{{route('smpp')}}">
                            <i class="fa fa-envelope-o" aria-hidden="true"></i> <span>SMPP</span>
                        </a>
                    </li>
                    <li @if(URL::current()==route('over_capacity'))  class="active" @endif>
                        <a href="{{route('over_capacity')}}">
                            <i class="fa fa-hourglass-end" aria-hidden="true"></i> <span>Over Capacity</span>
                        </a>
                    </li>
                </ul>
            </li>
            <li @if(strpos(URL::current(), route('setting')) !== false)  class="active treeview" @else
            class="treeview" @endif>
                <a href="#">
                    <i class="fa fa-gear"></i> <span>Settings</span>
                    <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
                </a>
                <ul class="treeview-menu">
                        <li @if(URL::current()==route('prefix_setting'))  class="active" @endif>
                            <a href="{{route('prefix_setting')}}">
                                <i class="fa fa-circle-o"></i> <span>Prefix</span>
                            </a>
                        </li>
                    <li @if(strpos(URL::current(), route('get_telerivet_info')) !== false)  class="active treeview" @else
                    class="treeview" @endif>
                        <a href="javascript:void(0);">
                            <img width="22" height="22" src="{{asset('assets/img/telerivet.png')}}" alt="Telerivet">
                            <span>Telerivet</span>
                            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
                        </a>
                        <ul  class="treeview-menu">
                            <li @if(URL::current()==route('get_telerivet_info'))  class="active" @endif>
                                <a href="{{route('get_telerivet_info')}}">
                                    <i class="fa fa-circle-o"></i> <span>Telerivet API</span>
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li @if(strpos(URL::current(), route('otp_vendor')) !== false)  class="active treeview" @else
                    class="treeview" @endif>
                        <a href="javascript:void(0);">
                            <i class="fa fa-product-hunt" aria-hidden="true"></i>
                            <span>OTP</span>
                            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
                        </a>
                        <ul  class="treeview-menu">
                            <li @if(URL::current()==route('otp_vendor'))  class="active" @endif>
                                <a href="{{route('otp_vendor')}}">
                                    <i class="fa fa-circle-o"></i>
                                    <span>Profiling</span>
                                </a>
                            </li>
                            <li @if(URL::current()==route('otp_input_string'))  class="active" @endif>
                                <a href="{{route('otp_input_string')}}">
                                    <i class="fa fa-circle-o"></i>
                                    <span>Input String</span>
                                </a>
                            </li>
                            <li @if(URL::current()==route('otp_output_string'))  class="active" @endif>
                                <a href="{{route('otp_output_string')}}">
                                    <i class="fa fa-circle-o"></i>
                                    <span>Output String</span>
                                </a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </li>

            <li @if(strpos(URL::current(), route('shortlink.shortlink')) !== false)  class="active treeview" @else
            class="treeview" @endif>
                <a href="javascript:void(0);">
                    <i class="fa fa-link" aria-hidden="true"></i> <span>Short Link</span>
                    <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
                </a>
                <ul  class="treeview-menu">
                    <li @if(URL::current()==route('shortlink.shortlink'))  class="active" @endif>
                        <a href="{{route('shortlink.shortlink')}}">
                            <i class="fa fa-circle-o"></i> Bit.ly Link
                        </a>
                    </li>
                    <li @if(URL::current()==route('shortlink.link'))  class="active" @endif>
                        <a href="{{route('shortlink.link')}}">
                            <i class="fa fa-circle-o"></i> Short Links
                        </a>
                    </li>
                    <li @if(URL::current()==route('shortlink.setting'))  class="active" @endif>
                        <a href="{{route('shortlink.setting')}}">
                            <i class="fa fa-circle-o"></i> Setting
                        </a>
                    </li>
                </ul>
            </li>
        </ul>
        <!-- /.sidebar-menu -->
    </section>
    <!-- /.sidebar -->
</aside>

resources/views/admin/include/top_sidebar.blade.php
<!-- Main Header -->
<header class="main-header">

    <!-- Logo -->
    <a href="{{route('home')}}" class="logo">
        <!-- mini logo for sidebar mini 50x50 pixels -->
        <span class="logo-mini"><b>S</b>MS</span>
        <!-- logo for regular state and mobile devices -->
        <span class="logo-lg text-left"><b>SMS</b> Admin</span>
    </a>
    <div class="no-padding hidden-md hidden-lg hidden-sm col-md-4">
        @php
            $time_zone = array();
            $timestamp = time();
            foreach(timezone_identifiers_list() as $key => $zone) {
                date_default_timezone_set($zone);
                $time_zone[$zone] = $zone.' ( ' . date('P', $timestamp)." )";
            }
        @endphp
        {!! Form::open(['route' => 'time_zone','class'=>'time_zone_form']) !!}

        {!! Form::select('time_zone', $time_zone, auth()->user()->time_zone, [
        'class'=>'form-control time_zone js-example-basic-single']); !!}
        {!! Form::close() !!}
    </div>

    <!-- Header Navbar -->
    <nav class="navbar navbar-static-top" role="navigation">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>
        <!-- Navbar Right Menu -->
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                <!-- Messages: style can be found in dropdown.less-->
                <li class="dropdown tasks-menu hidden-xs padding-top-8 custom-hide">


                    {!! Form::open(['route' => 'time_zone','class'=>'time_zone_form','class'=>'pull-right']) !!}

                    {!! Form::select('time_zone', $time_zone, auth()->user()->time_zone, [
            'class'=>'form-control time_zone js-example-basic-single']); !!}
                    {!! Form::close() !!}


                </li>


                <li @if(URL::current()==route('profile'))  class="profile-active dropdown user user-menu" @else
                class="dropdown user user-menu" @endif>
                    <!-- Menu Toggle Button -->
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <!-- The user image in the navbar-->
                        {{--<img src="{{asset('assets/img/user2-160x160.jpg')}}" class="user-image" alt="User Image">--}}
                        <i class="fa fa-user-o"></i>
                        <!-- hidden-xs hides the username on small devices so only the image appears. -->
                        <span class="hidden-xs">{{auth()->user()->name}}</span>
                    </a>
                    <ul class="dropdown-menu">
                        <!-- The user image in the menu -->
                        <li class="user-header">
                            <img src="{{asset('assets/img/user2-160x160.jpg')}}" class="img-circle" alt="User Image')}}">
                            <p>
                                {{auth()->user()->email}}

                            </p>
                        </li>
                        <!-- Menu Body -->
                        <!-- Menu Footer-->
                        <li class="user-footer">
                            <div class="pull-left">
                                <a href="{{route('profile')}}" class="btn btn-default btn-flat">Profile</a>
                            </div>
                            <div class="pull-right">
                                <a class="btn btn-default btn-flat" href="{{ route('admin.logout') }}">
                                    {{ __('Logout') }}
                                </a>

                            </div>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </nav>
</header>